# secrets.yaml

authentication:
  ProxycurlAPI:
    api_key: "your_proxycurl_api_key"
  CompanyDataAPI:
    api_key: "your_company_data_api_key"
  OpenAIAPI:
    api_key: "your_openai_api_key"
  Airtable:
    api_key: "your_airtable_api_key"
    base_id: "your_airtable_base_id"
  GoogleNewsAPI:
    api_key: "your_google_news_api_key"
  RedditAPI:
    client_id: "your_reddit_client_id"
    client_secret: "your_reddit_client_secret"
    user_agent: "your_app_name"
