customer_icp:
  profile_overview: Technical stakeholders within Insurance brokers that have a high likelihood of manual processes and procedures that need to be automated.
  weights:
    individual: 39
    company: 37
    technical: 12
    market: 12
  criteria:
    industries:
      - Insurance
      - Employee Benefits
      - Insurance Broker
    business_models:
      - B2B Services
    technologies:
      - SaaS
      - Client Portals
    locations:
      - United States
    growth_stages:
      - Enterprise
      - SMB
  target_departments:
    - IT
    - Engineering
    - Operations
  job_titles:
    - CTO
    - CIO
    - Director of IT
    - COO
  decision_making_authority:
    - Final Decision Maker
    - Key Influencer
    - Budget Holder
  negative_criteria: []
  required_skills: []
  minimum_requirements:
    employee_count_min: 50
    employee_count_max: 500
